#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.3.2
# In conjunction with Tcl version 8.6
#    Nov 19, 2014 01:52:58 PM
# Author: Prasanna Kannappan
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import cpsGameViewer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root, currGuiState
    root = Tk()
    root.title('CPS_Game')
    root.geometry('1301x744+65+24')
    #cpsGame_support.set_Tk_var()
    currGuiState = cpsGameViewer_support.guiState()
    w = CPS_Game (currGuiState, root)
    cpsGameViewer_support.init(root, w)
    root.mainloop()

w = None
def create_CPS_Game (root, currGuiState, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
        
    rt = root
    w = Toplevel (root)
    w.title('CPS_Game')
    w.geometry('1301x744+65+24')
    cpsGameViewer_support.set_Tk_var()
    w_win = CPS_Game (currGuiState, w)
    cpsGameViewer_support.init(w, w_win, param)
    return w_win

def destroy_CPS_Game ():
    global w, currGuiState
    currGuiState.destroyObjects()
    w.destroy()
    w = None


class CPS_Game:
    def __init__(self, currGuiState, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        master.configure(highlightcolor="black")

        self.btnSelectFile = Button (master,
                                     activebackground="#d9d9d9",
                                     text='''Select File''',
                                     command=currGuiState.selectFileCallback)

        self.btnReset = Button (master,
                                activebackground="#d9d9d9",
                                text='''Reset''',
                                state=DISABLED,
                                command=currGuiState.resetCallback)

        self.btnPrev = Button (master,
                               activebackground="#d9d9d9",
                               text='''<-- Prev''',
                               state=DISABLED,
                               command=currGuiState.prevCallback)

        self.btnNext = Button (master,
                               activebackground="#d9d9d9",
                               text='''Next -->''',
                               state=DISABLED,
                               command=currGuiState.nextCallback)

        self.canvasBoard = Canvas (master,
                                   background="white",
                                   borderwidth="2",
                                   relief=RIDGE,
                                   selectbackground="#c4c4c4")
        self.canvasBoard.bind("<Button-1>", currGuiState.prevCallback)        
 
        self.scrollbar = Scrollbar(master)
        
        self.txtOutput = Text (master,
                               background=_bgcolor,
                               relief=RIDGE,
                               font="TkTextFont",
                               selectbackground="#c4c4c4",
                               yscrollcommand=self.scrollbar.set)                       
        self.scrollbar.config(command=self.txtOutput.yview)
        
        self.canvasLegend = Canvas (master,
                            borderwidth="2",
                            selectbackground="#c4c4c4")

        master.bind("<Configure>", currGuiState.windowResizeCallback)

        # Position of GUI elements
        self.txtOutput.place(relx=0.57,rely=0.70,relheight=0.21,relwidth=0.38)
        self.scrollbar.place(relx=0.95,rely=0.70,relheight=0.21,relwidth=0.015)
        self.btnNext.place(relx=0.78,rely=0.55,height=60,width=200)
        self.btnPrev.place(relx=0.603,rely=0.55,height=60,width=200)
        self.btnSelectFile.place(relx=0.603,rely=0.04,height=117,width=200)
        self.btnReset.place(relx=0.78,rely=0.04,height=117,width=200)
        self.canvasBoard.place(relx=0.01,rely=0.01,relheight=0.91,relwidth=0.52)
        self.canvasLegend.place(relx=0.6,rely=0.25,relheight=0.25,relwidth=0.2)

        
        return

if __name__ == '__main__':
    vp_start_gui()



